// 定义BaseDummySize的item所需信息
export const BaseDummySizeItems = [
    {
        key: 'dummyHeight',
        name: 'height',
        label: 'Height',
        placeholder: 'Please enter height',
        required: false,
        intlId: 'component.uploadPattern.form.size.height',
    },
    {
        key: 'dummyBust',
        name: 'bust',
        label: 'Bust',
        placeholder: 'Please enter bust',
        required: false,
        intlId: 'component.uploadPattern.form.size.bust',
    },
    {
        key: 'dummyFrontLength',
        name: 'frontLength',
        label: 'Front length (SNP to Hem)',
        placeholder: 'Please enter front length (SNP to Hem)',
        required: false,
        intlId: 'component.uploadPattern.form.size.frontLength',
    },
    {
        key: 'dummyBackLength',
        name: 'backLength',
        label: 'Back length (SNP to Hem)',
        placeholder: 'Please enter back length (SNP to Hem)',
        required: false,
        intlId: 'component.uploadPattern.form.size.backLength',
    },
    {
        key: 'dummyBackLengthBNP',
        name: 'backLengthBNP',
        label: 'Back length (BNP to Waist)',
        placeholder: 'Please enter back length (BNP to Waist)',
        required: false,
        intlId: 'component.uploadPattern.form.size.backLengthBNP',
    },
    {
        key: 'dummyWaist',
        name: 'waist',
        label: 'Waist',
        placeholder: 'Please enter waist',
        required: false,
        intlId: 'component.uploadPattern.form.size.waist',
    },

    {
        key: 'dummyWaistTrousers',
        name: 'waistTrousers',
        label: 'Waist (trousers)',
        placeholder: 'Please enter waist (trousers)',
        required: false,
        intlId: 'component.uploadPattern.form.size.waistTrousers',
    },
    {
        key: 'dummyHighHip',
        name: 'highHip',
        label: 'High hip',
        placeholder: 'Please enter high hip',
        required: false,
        intlId: 'component.uploadPattern.form.size.highHip',
    },
    {
        key: 'dummyHip',
        name: 'hip',
        label: 'Hip',
        placeholder: 'Please enter hip',
        required: false,
        intlId: 'component.uploadPattern.form.size.hip',
    },
    {
        key: 'dummyInseam',
        name: 'inseam',
        label: 'Inseam',
        placeholder: 'Please enter inseam',
        required: false,
        intlId: 'component.uploadPattern.form.size.inseam',
    },

    {
        key: 'dummyOutseam',
        name: 'outseam',
        label: 'Outseam',
        placeholder: 'Please enter outseam',
        required: false,
        intlId: 'component.uploadPattern.form.size.outseam',
    },
    {
        key: 'dummyArmlength',
        name: 'armlength',
        label: 'Armlength',
        placeholder: 'Please enter armlength',
        required: false,
        intlId: 'component.uploadPattern.form.size.armlength',
    },
    {
        key: 'dummyAcrossShoulder',
        name: 'acrossShoulder',
        label: 'Across Shoulder',
        placeholder: 'Please enter across shoulder',
        required: false,
        intlId: 'component.uploadPattern.form.size.acrossShoulder',
    },
    {
        key: 'dummyShoulderLength',
        name: 'shoulderLength',
        label: 'Shoulder length',
        placeholder: 'Please enter Shoulder length',
        required: false,
        intlId: 'component.uploadPattern.form.size.shoulderLength',
    },
    {
        key: 'dummyAbdomen',
        name: 'abdomen',
        label: 'Abdomen',
        placeholder: 'Please enter abdomen',
        required: false,
        intlId: 'component.uploadPattern.form.size.abdomen',
    },

    {
        key: 'dummyThigh',
        name: 'thigh',
        label: 'Thigh',
        placeholder: 'Please enter thigh',
        required: false,
        intlId: 'component.uploadPattern.form.size.thigh',
    },
    {
        key: 'dummyKnee',
        name: 'knee',
        label: 'Knee',
        placeholder: 'Please enter knee',
        required: false,
        intlId: 'component.uploadPattern.form.size.knee',
    },
    {
        key: 'dummyCalf',
        name: 'calf',
        label: 'Calf',
        placeholder: 'Please enter calf',
        required: false,
        intlId: 'component.uploadPattern.form.size.calf',
    },
    {
        key: 'dummyAnkle',
        name: 'ankle',
        label: 'Ankle',
        placeholder: 'Please enter ankle',
        required: false,
        intlId: 'component.uploadPattern.form.size.ankle',
    },

    {
        key: 'dummyDartWidth',
        name: 'dartWidth',
        label: 'Dart width',
        placeholder: 'Please enter dart width',
        required: false,
        intlId: 'component.uploadPattern.form.size.dartWidth',
    },
    {
        key: 'dummyCrotchHeight',
        name: 'crotchHeight',
        label: 'Crotch height (front piece)',
        placeholder: 'Please enter crotch height (front piece)',
        required: false,
        intlId: 'component.uploadPattern.form.size.crotchHeight',
    },
    {
        key: 'dummyRise',
        name: 'rise',
        label: 'Rise',
        placeholder: 'Please enter rise',
        required: false,
        intlId: 'component.uploadPattern.form.size.rise',
    },
    {
        key: 'dummyCollarWidth',
        name: 'collarWidth',
        label: 'Collar width',
        placeholder: 'Please enter collar width',
        required: false,
        intlId: 'component.uploadPattern.form.size.collarWidth',
    },
    {
        key: 'dummyHem',
        name: 'hem',
        label: 'Hem',
        placeholder: 'Please enter hem',
        required: false,
        intlId: 'component.uploadPattern.form.size.hem',
    },
    {
        key: 'dummyWaistband',
        name: 'waistband',
        label: 'Waistband',
        placeholder: 'Please enter waistband',
        required: false,
        intlId: 'component.uploadPattern.form.size.waistband',
    },
];

// 定义BasePatternSize的item所需信息
export const BasePatternSizeItems = [
    {
        key: 'patternHeight',
        name: 'height',
        label: 'Height',
        placeholder: 'Please enter height',
        required: false,
        intlId: 'component.uploadPattern.form.size.height',
    },
    {
        key: 'patternBust',
        name: 'bust',
        label: 'Bust',
        placeholder: 'Please enter bust',
        required: false,
        intlId: 'component.uploadPattern.form.size.bust',
    },
    {
        key: 'patternFrontLength',
        name: 'frontLength',
        label: 'Front length (SNP to Hem)',
        placeholder: 'Please enter front length (SNP to Hem)',
        required: false,
        intlId: 'component.uploadPattern.form.size.frontLength',
    },
    {
        key: 'patternBackLength',
        name: 'backLength',
        label: 'Back length (SNP to Hem)',
        placeholder: 'Please enter back length (SNP to Hem)',
        required: false,
        intlId: 'component.uploadPattern.form.size.backLength',
    },
    {
        key: 'patternBackLengthBNP',
        name: 'backLengthBNP',
        label: 'Back length (BNP to Waist)',
        placeholder: 'Please enter back length (BNP to Waist)',
        required: false,
        intlId: 'component.uploadPattern.form.size.backLengthBNP',
    },
    {
        key: 'patternWaist',
        name: 'waist',
        label: 'Waist',
        placeholder: 'Please enter waist',
        required: false,
        intlId: 'component.uploadPattern.form.size.waist',
    },
    {
        key: 'patternWaistTrousers',
        name: 'waistTrousers',
        label: 'Waist (trousers)',
        placeholder: 'Please enter waist (trousers)',
        required: false,
        intlId: 'component.uploadPattern.form.size.waistTrousers',
    },
    {
        key: 'patternHighHip',
        name: 'highHip',
        label: 'High hip',
        placeholder: 'Please enter high hip',
        required: false,
        intlId: 'component.uploadPattern.form.size.highHip',
    },
    {
        key: 'patternHip',
        name: 'hip',
        label: 'Hip',
        placeholder: 'Please enter hip',
        required: false,
        intlId: 'component.uploadPattern.form.size.hip',
    },
    {
        key: 'patternInseam',
        name: 'inseam',
        label: 'Inseam',
        placeholder: 'Please enter inseam',
        required: false,
        intlId: 'component.uploadPattern.form.size.inseam',
    },
    {
        key: 'patternOutseam',
        name: 'outseam',
        label: 'Outseam',
        placeholder: 'Please enter outseam',
        required: false,
        intlId: 'component.uploadPattern.form.size.outseam',
    },
    {
        key: 'patternArmlength',
        name: 'armlength',
        label: 'Armlength',
        placeholder: 'Please enter armlength',
        required: false,
        intlId: 'component.uploadPattern.form.size.armlength',
    },
    {
        key: 'patternAcrossShoulder',
        name: 'acrossShoulder',
        label: 'Across Shoulder',
        placeholder: 'Please enter across shoulder',
        required: false,
        intlId: 'component.uploadPattern.form.size.acrossShoulder',
    },
    {
        key: 'patternShoulderLength',
        name: 'shoulderLength',
        label: 'Shoulder length',
        placeholder: 'Please enter Shoulder length',
        required: false,
        intlId: 'component.uploadPattern.form.size.shoulderLength',
    },
    {
        key: 'patternAbdomen',
        name: 'abdomen',
        label: 'Abdomen',
        placeholder: 'Please enter abdomen',
        required: false,
        intlId: 'component.uploadPattern.form.size.abdomen',
    },
    {
        key: 'patternThigh',
        name: 'thigh',
        label: 'Thigh',
        placeholder: 'Please enter thigh',
        required: false,
        intlId: 'component.uploadPattern.form.size.thigh',
    },
    {
        key: 'patternKnee',
        name: 'knee',
        label: 'Knee',
        placeholder: 'Please enter knee',
        required: false,
        intlId: 'component.uploadPattern.form.size.knee',
    },
    {
        key: 'patternCalf',
        name: 'calf',
        label: 'Calf',
        placeholder: 'Please enter calf',
        required: false,
        intlId: 'component.uploadPattern.form.size.calf',
    },
    {
        key: 'patternAnkle',
        name: 'ankle',
        label: 'Ankle',
        placeholder: 'Please enter ankle',
        required: false,
        intlId: 'component.uploadPattern.form.size.ankle',
    },
    {
        key: 'patternDartWidth',
        name: 'dartWidth',
        label: 'Dart width',
        placeholder: 'Please enter dart width',
        required: false,
        intlId: 'component.uploadPattern.form.size.dartWidth',
    },
    {
        key: 'patternCrotchHeight',
        name: 'crotchHeight',
        label: 'Crotch height (front piece)',
        placeholder: 'Please enter crotch height (front piece)',
        required: false,
        intlId: 'component.uploadPattern.form.size.crotchHeight',
    },
    {
        key: 'patternRise',
        name: 'rise',
        label: 'Rise',
        placeholder: 'Please enter rise',
        required: false,
        intlId: 'component.uploadPattern.form.size.rise',
    },
    {
        key: 'patternCollarWidth',
        name: 'collarWidth',
        label: 'Collar width',
        placeholder: 'Please enter collar width',
        required: false,
        intlId: 'component.uploadPattern.form.size.collarWidth',
    },
    {
        key: 'patternHem',
        name: 'hem',
        label: 'Hem',
        placeholder: 'Please enter hem',
        required: false,
        intlId: 'component.uploadPattern.form.size.hem',
    },
    {
        key: 'patternWaistband',
        name: 'waistband',
        label: 'Waistband',
        placeholder: 'Please enter waistband',
        required: false,
        intlId: 'component.uploadPattern.form.size.waistband',
    },
];
